import type { Category, Product, StoreSettings } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  { id: "c1", name: "Verduras", slug: "verduras", icon: "Leaf", sort_order: 1, is_active: true },
  { id: "c2", name: "Frutas", slug: "frutas", icon: "Apple", sort_order: 2, is_active: true },
  { id: "c3", name: "Legumes", slug: "legumes", icon: "Carrot", sort_order: 3, is_active: true },
  { id: "c4", name: "Temperos", slug: "temperos", icon: "Sprout", sort_order: 4, is_active: true },
  { id: "c5", name: "Orgânicos", slug: "organicos", icon: "Flower2", sort_order: 5, is_active: true },
  { id: "c6", name: "Grãos", slug: "graos", icon: "Wheat", sort_order: 6, is_active: true },
  { id: "c7", name: "Laticínios", slug: "laticinios", icon: "Milk", sort_order: 7, is_active: true },
  { id: "c8", name: "Bebidas", slug: "bebidas", icon: "CupSoda", sort_order: 8, is_active: true },
  { id: "c9", name: "Outros", slug: "outros", icon: "Package", sort_order: 9, is_active: true },
];

const img = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=800&q=80`;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Cenoura Orgânica",
    slug: "cenoura-organica",
    description:
      "Cenouras cultivadas sem agrotóxicos, colhidas na semana. Doces, crocantes e cheias de betacaroteno.",
    category_id: "c3",
    base_price: 9.5,
    unit_prices: { unidade: 2.5, "500g": 5, "1kg": 9.5 },
    promotional_price: 8,
    promotional_start: null,
    promotional_end: null,
    stock: { unidade: 50, "500g": 30, "1kg": 20 },
    images: [img("photo-1598170845058-32b9d6a5da37")],
    tags: ["orgânico", "sem agrotóxicos"],
    is_active: true,
    is_featured: true,
    nutritional_info: { calories: 41, protein: 0.9, carbs: 9.6, fiber: 2.8 },
  },
  {
    id: "p2",
    name: "Alface Crespa",
    slug: "alface-crespa",
    description: "Alface fresquinha, colhida no dia. Folhas macias e sabor inigualável.",
    category_id: "c1",
    base_price: 4.5,
    unit_prices: { unidade: 4.5, maço: 4.5 },
    promotional_price: null,
    stock: { unidade: 40, maço: 40 },
    images: [img("photo-1622206151226-18ca2c9ab4a1")],
    tags: ["folhosa"],
    is_active: true,
    is_featured: true,
  },
  {
    id: "p3",
    name: "Tomate Italiano",
    slug: "tomate-italiano",
    description: "Tomates italianos maduros, perfeitos para molhos e saladas.",
    category_id: "c3",
    base_price: 12.9,
    unit_prices: { "500g": 6.9, "1kg": 12.9 },
    promotional_price: null,
    stock: { "500g": 25, "1kg": 15 },
    images: [img("photo-1592924357228-91a4daadcfea")],
    tags: [],
    is_active: true,
    is_featured: true,
  },
  {
    id: "p4",
    name: "Banana Prata Orgânica",
    slug: "banana-prata-organica",
    description: "Doces e maduras na medida certa, cultivadas sem agrotóxicos.",
    category_id: "c2",
    base_price: 8.5,
    unit_prices: { dúzia: 8.5, "1kg": 7.9 },
    promotional_price: 6.9,
    stock: { dúzia: 30, "1kg": 20 },
    images: [img("photo-1571771894821-ce9b6c11b08e")],
    tags: ["orgânico"],
    is_active: true,
    is_featured: true,
  },
  {
    id: "p5",
    name: "Manjericão Fresco",
    slug: "manjericao-fresco",
    description: "Molho fresco e aromático, colhido no dia.",
    category_id: "c4",
    base_price: 3.5,
    unit_prices: { maço: 3.5 },
    promotional_price: null,
    stock: { maço: 25 },
    images: [img("photo-1618375569909-3c8616cca7d4")],
    tags: ["fresco"],
    is_active: true,
    is_featured: false,
  },
  {
    id: "p6",
    name: "Ovos Caipiras",
    slug: "ovos-caipiras",
    description: "Ovos de galinhas criadas soltas, alimentadas com milho não transgênico.",
    category_id: "c7",
    base_price: 18.0,
    unit_prices: { dúzia: 18, bandeja: 42 },
    promotional_price: null,
    stock: { dúzia: 20, bandeja: 10 },
    images: [img("photo-1489761486274-a2c4b6d8ef37")],
    tags: ["caipira", "livre de gaiolas"],
    is_active: true,
    is_featured: true,
  },
  {
    id: "p7",
    name: "Feijão Preto Orgânico",
    slug: "feijao-preto-organico",
    description: "Feijão preto orgânico, selecionado grão a grão.",
    category_id: "c6",
    base_price: 14.9,
    unit_prices: { pacote: 14.9, "1kg": 14.9 },
    promotional_price: null,
    stock: { pacote: 40, "1kg": 40 },
    images: [img("photo-1615485500704-8e990f9900f7")],
    tags: ["orgânico"],
    is_active: true,
    is_featured: false,
  },
  {
    id: "p8",
    name: "Suco de Laranja Natural 1L",
    slug: "suco-laranja-natural",
    description: "Suco de laranja pêra 100% natural, sem açúcar ou conservantes.",
    category_id: "c8",
    base_price: 15.0,
    unit_prices: { litro: 15, unidade: 15 },
    promotional_price: null,
    stock: { litro: 15, unidade: 15 },
    images: [img("photo-1600271886742-f049cd451bba")],
    tags: ["natural"],
    is_active: true,
    is_featured: true,
  },
];

export const MOCK_SETTINGS: StoreSettings = {
  id: "s1",
  name: "Feirinha Orgânica - Terra Viva",
  description: "Produtos orgânicos frescos direto da terra para sua mesa.",
  whatsapp: "5511999998888",
  phone: "(11) 3333-4444",
  email: "contato@terraviva.com.br",
  address: "Rua das Hortas, 123 — Vila Verde, São Paulo/SP",
  logo_url: undefined,
  cover_url: undefined,
  primary_color: "#059669",
  secondary_color: "#d97706",
  opening_hours: {
    seg: { open: "08:00", close: "18:00", closed: false },
    ter: { open: "08:00", close: "18:00", closed: false },
    qua: { open: "08:00", close: "18:00", closed: false },
    qui: { open: "08:00", close: "18:00", closed: false },
    sex: { open: "08:00", close: "18:00", closed: false },
    sab: { open: "08:00", close: "13:00", closed: false },
    dom: { open: "08:00", close: "12:00", closed: true },
  },
  delivery_fee: 8,
  delivery_type: "fixed",
  delivery_distance_rates: [
    { from_km: 0, to_km: 3, fee: 5 },
    { from_km: 3, to_km: 7, fee: 10 },
    { from_km: 7, to_km: 15, fee: 18 },
  ],
  delivery_time_min: 45,
  delivery_radius_km: 10,
  pix_enabled: true,
  pix_key: "contato@terraviva.com.br",
  pix_key_type: "email",
  cash_enabled: true,
  card_enabled: true,
  about_text:
    "Somos uma feirinha de bairro dedicada a levar alimentos orgânicos, frescos e saudáveis para a sua família. Trabalhamos direto com pequenos produtores locais.",
  about_images: [],
};

export const MOCK_COUPON = {
  id: "cp1",
  code: "ORGANICO10",
  type: "percentage" as const,
  value: 10,
  max_uses: 100,
  current_uses: 0,
  start_date: new Date().toISOString(),
  end_date: new Date(Date.now() + 90 * 86400000).toISOString(),
  applicable_products: null,
  is_active: true,
};
